name: Publish Tutorial

on:
  push:
    branches:
      - docs

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs branch
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Set GIT user
        run: |
          git config user.email "gh-actions@moes-media.be"
          git config user.name "gh-actions bot"
      - name: Build site
        run: yarn site:build
      - name: Deploy site to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/site/public
