name: Publish Tutorial

on:
  push:
    branches:
      - docs

jobs:
  build-site:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install
      - run: yarn deploy
