name: Tag chapter code
on:
  push:
    branches:
      - feature/project-setup

jobs:
  tag-chapter-code-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Trim branch name
        uses: actions/github-script@v5
        with:
          script: return "${{ steps.extract_branch.outputs.branch }}".replace(/feature\//, '');
          result-encoding: string
        id: trim-branch
      - name: Print trimmed branch name
        run: echo "${{ steps.trim-branch.outputs.result }}"
