name: Tag chapter code
on:
  push:
    branches:
      - feature/project-setup

jobs:
  Tag Chapter Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: |
          BRANCH="##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo $BRANCH
          STR="${BRANCH//(^[ ]+|[ ]+$)/}"
          echo $STR
        id: extract_branch