name: Tag chapter code
on:
  push:
    branches:
      - feature/project-setup

jobs:
  tag-chapter-code-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Print branch name
        run: echo ${${{ steps.extract_branch.outputs.branch }}//feature\//}
